name: Sync Fork with Rebase

on:
  schedule:
    - cron: '0 0 * * *' # Esegue ogni giorno a mezzanotte
  workflow_dispatch: # Permette di eseguire manualmente il workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessario per il rebase

    - name: Set up Git user
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/qwertyuiop8899/streamvix.git
        git fetch upstream
        git rebase upstream/main

    # AGGIUNTA: Configura git per usare il Personal Access Token (PAT)
    - name: Configura git per PAT
      run: git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Push changes
      run: git push --force-with-lease origin main
